# Generated by Django 3.2.4 on 2021-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_num', models.IntegerField(default=0)),
                ('slide_image', models.ImageField(default='', upload_to='app/images')),
                ('slide_title', models.CharField(max_length=30)),
                ('slide_details', models.CharField(max_length=60)),
            ],
        ),
    ]
