# Generated by Django 3.2.4 on 2021-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_slider_slide_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_event_date', models.DateField()),
                ('up_event_title', models.CharField(max_length=30)),
                ('up_event_details', models.CharField(max_length=50)),
                ('up_event_image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
    ]
