# Generated by Django 3.2.4 on 2021-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210818_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bas_name', models.CharField(max_length=30)),
                ('bas_batch', models.IntegerField()),
                ('bas_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_name', models.CharField(max_length=30)),
                ('cri_batch', models.IntegerField()),
                ('cri_image', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_name', models.CharField(max_length=30)),
                ('foot_batch', models.IntegerField()),
                ('foot_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TableTennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_name', models.CharField(max_length=30)),
                ('tt_batch', models.IntegerField()),
                ('tt_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
