# Generated by Django 3.2.4 on 2021-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_basketball_cricket_football_tabletennis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket',
            name='cri_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
