# Generated by Django 3.2.4 on 2021-08-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='b_ling',
            new_name='b_link',
        ),
    ]
