# Generated by Django 3.2.4 on 2021-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_blog_b_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='badminton',
            name='bad_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketball',
            name='bas_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cricket',
            name='cri_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='football',
            name='foot_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subeb',
            name='s_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletennis',
            name='tt_major',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
