# Generated by Django 3.2.4 on 2021-07-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slide_num',
        ),
    ]
