# Generated by Django 3.2.4 on 2021-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badminton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_name', models.CharField(max_length=30)),
                ('bad_batch', models.IntegerField()),
                ('bad_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
