# Generated by Django 3.2.4 on 2021-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cricket_cri_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_batch', models.IntegerField()),
                ('s_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
