# Generated by Django 3.2.4 on 2021-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_b_ling_blog_b_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_link',
            field=models.URLField(),
        ),
    ]
